apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-MyFlask
spec:
  selector:
    env: prod
    app: {{.Release.Name}}-MyFlask
  ports:
  - port      : 8080
    targetPort: 8080
    protocol  : TCP
  type: NodePort