apiVersion: v1
kind: ConfigMap
metadata:
  name: first-cm
  namespace: lesson16
data:
  config.yaml: |
    colorgood: purple
    colorbad: yellow
spec:
  containers:
    - name: web
      image: ksxack/lesson1:v0.2
      ports:
        - containerPort: 8080
      env:
        - name: COLORGOOD
          valueFrom:
            configMapKeyRef:
              name: env-cm
              key: colorgood
        - name: COLORBAD
          valueFrom:
            configMapKeyRef:
              name: env-cm
              key: colorbad