apiVersion: v1
kind: Pod
metadata:
  name: pod-v1
  labels:
    name: myapp
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "50m" 
    ports:
      - containerPort: 80
