kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ivanov_aa-reader-pods
  namespace: lesson2
subjects:
- kind: User
  name: ivanov_aa
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io