apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      project: dev
  template:
    metadata:
      labels:
        app: myapp
        project: dev
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: redis
        image: redis
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service-multi
  labels:
    app: myapp
    env: prod
spec:
  selector:
    app: redis, nginx
    project: dev
  ports:
  - port      : 8080 #PORT ON LB
    name      : app-listen
    targetPort: 8080 #PORT ON POD
    protocol  : TCP
  type: NodePort
