apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      project: prod
  template:
    metadata:
      labels:
        app: myapp
        project: prod
    spec:
      containers:
      - name: myapp
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service-node
spec:
  selector:
    app: myapp
    project: prod
  ports:
  - port: 80
    nodePort: 30080
  type: NodePort
