apiVersion: v1
kind: Pod
metadata:
  name: pod-v2
  labels:
    name: myapp
    env : prod
    tier: front
    app : myapp
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "50m" 
    ports:
      - containerPort: 80
  - name: redis
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "50m" 
    ports:
      - containerPort: 90
